/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as dashboardRouteImport } from './routes/dashboard'
import { Route as adminRouteImport } from './routes/admin'
import { Route as assistantRouteImport } from './routes/assistant'
import { Route as registerRouteImport } from './routes/register'
import { Route as customersRouteImport } from './routes/customers'
import { Route as connectionsRouteImport } from './routes/connections'
import { Route as storeOnboardingRouteImport } from './routes/storeOnboarding'
import { Route as moneyRouteImport } from './routes/money'
import { Route as loginRouteImport } from './routes/login'
import { Route as managementRouteImport } from './routes/management'
import { Route as influencersRouteImport } from './routes/influencers'
import { Route as logisticsRouteImport } from './routes/logistics'
import { Route as storeRouteImport } from './routes/store'
import { Route as marketingRouteImport } from './routes/marketing'
import { Route as goalsRouteImport } from './routes/goals'
import { Route as analysisRouteImport } from './routes/analysis'
import { Route as ordersRouteImport } from './routes/orders'
import { Route as productsRouteImport } from './routes/products'

const dashboardRoute = dashboardRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const adminRoute = adminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const assistantRoute = assistantRouteImport.update({
  id: '/assistente',
  path: '/assistente',
  getParentRoute: () => rootRouteImport,
} as any)
const registerRoute = registerRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const customersRoute = customersRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const connectionsRoute = connectionsRouteImport.update({
  id: '/conexoes',
  path: '/conexoes',
  getParentRoute: () => rootRouteImport,
} as any)
const storeOnboardingRoute = storeOnboardingRouteImport.update({
  id: '/configurar-loja',
  path: '/configurar-loja',
  getParentRoute: () => rootRouteImport,
} as any)
const moneyRoute = moneyRouteImport.update({
  id: '/dinheiro',
  path: '/dinheiro',
  getParentRoute: () => rootRouteImport,
} as any)
const loginRoute = loginRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const managementRoute = managementRouteImport.update({
  id: '/gestao',
  path: '/gestao',
  getParentRoute: () => rootRouteImport,
} as any)
const influencersRoute = influencersRouteImport.update({
  id: '/influenciadores',
  path: '/influenciadores',
  getParentRoute: () => rootRouteImport,
} as any)
const logisticsRoute = logisticsRouteImport.update({
  id: '/logistica',
  path: '/logistica',
  getParentRoute: () => rootRouteImport,
} as any)
const storeRoute = storeRouteImport.update({
  id: '/loja',
  path: '/loja',
  getParentRoute: () => rootRouteImport,
} as any)
const marketingRoute = marketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const goalsRoute = goalsRouteImport.update({
  id: '/metas',
  path: '/metas',
  getParentRoute: () => rootRouteImport,
} as any)
const analysisRoute = analysisRouteImport.update({
  id: '/metricas',
  path: '/metricas',
  getParentRoute: () => rootRouteImport,
} as any)
const ordersRoute = ordersRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => rootRouteImport,
} as any)
const productsRoute = productsRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof dashboardRoute
  '/admin': typeof adminRoute
  '/assistente': typeof assistantRoute
  '/cadastro': typeof registerRoute
  '/clientes': typeof customersRoute
  '/conexoes': typeof connectionsRoute
  '/configurar-loja': typeof storeOnboardingRoute
  '/dinheiro': typeof moneyRoute
  '/entrar': typeof loginRoute
  '/gestao': typeof managementRoute
  '/influenciadores': typeof influencersRoute
  '/logistica': typeof logisticsRoute
  '/loja': typeof storeRoute
  '/marketing': typeof marketingRoute
  '/metas': typeof goalsRoute
  '/metricas': typeof analysisRoute
  '/pedidos': typeof ordersRoute
  '/produtos': typeof productsRoute
}
export interface FileRoutesByTo {
  '/': typeof dashboardRoute
  '/admin': typeof adminRoute
  '/assistente': typeof assistantRoute
  '/cadastro': typeof registerRoute
  '/clientes': typeof customersRoute
  '/conexoes': typeof connectionsRoute
  '/configurar-loja': typeof storeOnboardingRoute
  '/dinheiro': typeof moneyRoute
  '/entrar': typeof loginRoute
  '/gestao': typeof managementRoute
  '/influenciadores': typeof influencersRoute
  '/logistica': typeof logisticsRoute
  '/loja': typeof storeRoute
  '/marketing': typeof marketingRoute
  '/metas': typeof goalsRoute
  '/metricas': typeof analysisRoute
  '/pedidos': typeof ordersRoute
  '/produtos': typeof productsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof dashboardRoute
  '/admin': typeof adminRoute
  '/assistente': typeof assistantRoute
  '/cadastro': typeof registerRoute
  '/clientes': typeof customersRoute
  '/conexoes': typeof connectionsRoute
  '/configurar-loja': typeof storeOnboardingRoute
  '/dinheiro': typeof moneyRoute
  '/entrar': typeof loginRoute
  '/gestao': typeof managementRoute
  '/influenciadores': typeof influencersRoute
  '/logistica': typeof logisticsRoute
  '/loja': typeof storeRoute
  '/marketing': typeof marketingRoute
  '/metas': typeof goalsRoute
  '/metricas': typeof analysisRoute
  '/pedidos': typeof ordersRoute
  '/produtos': typeof productsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/assistente'
    | '/cadastro'
    | '/clientes'
    | '/conexoes'
    | '/configurar-loja'
    | '/dinheiro'
    | '/entrar'
    | '/gestao'
    | '/influenciadores'
    | '/logistica'
    | '/loja'
    | '/marketing'
    | '/metas'
    | '/metricas'
    | '/pedidos'
    | '/produtos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/assistente'
    | '/cadastro'
    | '/clientes'
    | '/conexoes'
    | '/configurar-loja'
    | '/dinheiro'
    | '/entrar'
    | '/gestao'
    | '/influenciadores'
    | '/logistica'
    | '/loja'
    | '/marketing'
    | '/metas'
    | '/metricas'
    | '/pedidos'
    | '/produtos'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/assistente'
    | '/cadastro'
    | '/clientes'
    | '/conexoes'
    | '/configurar-loja'
    | '/dinheiro'
    | '/entrar'
    | '/gestao'
    | '/influenciadores'
    | '/logistica'
    | '/loja'
    | '/marketing'
    | '/metas'
    | '/metricas'
    | '/pedidos'
    | '/produtos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  dashboardRoute: typeof dashboardRoute
  adminRoute: typeof adminRoute
  assistantRoute: typeof assistantRoute
  registerRoute: typeof registerRoute
  customersRoute: typeof customersRoute
  connectionsRoute: typeof connectionsRoute
  storeOnboardingRoute: typeof storeOnboardingRoute
  moneyRoute: typeof moneyRoute
  loginRoute: typeof loginRoute
  managementRoute: typeof managementRoute
  influencersRoute: typeof influencersRoute
  logisticsRoute: typeof logisticsRoute
  storeRoute: typeof storeRoute
  marketingRoute: typeof marketingRoute
  goalsRoute: typeof goalsRoute
  analysisRoute: typeof analysisRoute
  ordersRoute: typeof ordersRoute
  productsRoute: typeof productsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof dashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof adminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistente': {
      id: '/assistente'
      path: '/assistente'
      fullPath: '/assistente'
      preLoaderRoute: typeof assistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof registerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof customersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conexoes': {
      id: '/conexoes'
      path: '/conexoes'
      fullPath: '/conexoes'
      preLoaderRoute: typeof connectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configurar-loja': {
      id: '/configurar-loja'
      path: '/configurar-loja'
      fullPath: '/configurar-loja'
      preLoaderRoute: typeof storeOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dinheiro': {
      id: '/dinheiro'
      path: '/dinheiro'
      fullPath: '/dinheiro'
      preLoaderRoute: typeof moneyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrar': {
      id: '/entrar'
      path: '/entrar'
      fullPath: '/entrar'
      preLoaderRoute: typeof loginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gestao': {
      id: '/gestao'
      path: '/gestao'
      fullPath: '/gestao'
      preLoaderRoute: typeof managementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/influenciadores': {
      id: '/influenciadores'
      path: '/influenciadores'
      fullPath: '/influenciadores'
      preLoaderRoute: typeof influencersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logistica': {
      id: '/logistica'
      path: '/logistica'
      fullPath: '/logistica'
      preLoaderRoute: typeof logisticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loja': {
      id: '/loja'
      path: '/loja'
      fullPath: '/loja'
      preLoaderRoute: typeof storeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketing': {
      id: '/marketing'
      path: '/marketing'
      fullPath: '/marketing'
      preLoaderRoute: typeof marketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metas': {
      id: '/metas'
      path: '/metas'
      fullPath: '/metas'
      preLoaderRoute: typeof goalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metricas': {
      id: '/metricas'
      path: '/metricas'
      fullPath: '/metricas'
      preLoaderRoute: typeof analysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedidos': {
      id: '/pedidos'
      path: '/pedidos'
      fullPath: '/pedidos'
      preLoaderRoute: typeof ordersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtos': {
      id: '/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof productsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  dashboardRoute: dashboardRoute,
  adminRoute: adminRoute,
  assistantRoute: assistantRoute,
  registerRoute: registerRoute,
  customersRoute: customersRoute,
  connectionsRoute: connectionsRoute,
  storeOnboardingRoute: storeOnboardingRoute,
  moneyRoute: moneyRoute,
  loginRoute: loginRoute,
  managementRoute: managementRoute,
  influencersRoute: influencersRoute,
  logisticsRoute: logisticsRoute,
  storeRoute: storeRoute,
  marketingRoute: marketingRoute,
  goalsRoute: goalsRoute,
  analysisRoute: analysisRoute,
  ordersRoute: ordersRoute,
  productsRoute: productsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
