import { index, rootRoute, route } from "@tanstack/virtual-file-routes";

export const routes = rootRoute("__root.tsx", [
  index("dashboard.tsx"),
  route("/entrar", "login.tsx"),
  route("/cadastro", "register.tsx"),
  route("/esqueci-senha", "forgotPassword.tsx"),
  route("/redefinir-senha", "resetPassword.tsx"),
  route("/configurar-loja", "storeOnboarding.tsx"),
  route("/loja", "store.tsx"),
  route("/loja-arquivada", "storeArchived.tsx"),
  route("/em-desenvolvimento", "underDevelopment.tsx"),
  route("/admin", "adminLayout.tsx", [
    index("admin.tsx"),
    route("/usuarios", "adminUsers.tsx"),
    route("/acesso", "adminAccess.tsx"),
  ]),
  route("/dinheiro", "money.tsx"),
  route("/marketing", "marketing.tsx"),
  route("/logistica", "logistics.tsx"),
  route("/gestao", "management.tsx"),
  route("/integracoes", "connections.tsx"),
  route("/conexoes", "legacyConnections.tsx"),
  route("/assistente", "assistant.tsx"),
  route("/pedidos", "orders.tsx"),
  route("/produtos", "products.tsx"),
  route("/clientes", "customers.tsx"),
  route("/metas", "goals.tsx"),
  route("/metricas", "analysis.tsx"),
  route("/influenciadores", "influencers.tsx"),
]);
