export {
  adPlatformLabel,
  adPlatforms,
  audienceDimensionLabel,
  audienceDimensions,
  funnelStageLabel,
  funnelStages,
  discountMetricKeys,
  socialPlatformLabel,
  socialPlatforms,
} from "./marketing.types";
export type {
  AudienceDimension,
  FunnelStage,
  FunnelStepDelta,
  MarketingGeneral,
  PlatformCard,
  SalesInvestmentPoint,
  TrafficPoint,
  ChannelRoas,
  ChannelSales,
  AdPlatform,
  TrafficAggregate,
  TrafficBucket,
  AdSpendAggregate,
  AdSpendBucket,
  MarketingCostLine,
  MarketingRetention,
  MarketingOverview,
  ChannelPerformanceRow,
  FunnelStepValue,
  FunnelRatioRow,
  UtmSalesRow,
  MarketingSummary,
  AdPerformanceRow,
  MarketingCampaigns,
  DiscountCodeRow,
  DiscountMetricKey,
  DiscountMetric,
  MarketingDiscounts,
  RegionPerformanceRow,
  MarketingRegions,
  SocialPlatform,
  SocialAccountRow,
  SocialPostRow,
  MarketingSocial,
  StaleSource,
  MarketingVisao,
  MarketingScreen,
} from "./marketing.types";
export {
  investmentMetricLabel,
  sessionMetricLabel,
  utmDimensionLabel,
  adLevelLabel,
  adMetricLabel,
} from "./marketingLabels";
export {
  roasBands,
  platformFeeRate,
  roasQualityLabel,
  roasQuality,
  funnelSteps,
  funnelStepLabel,
  funnelRatios,
  funnelRatio,
  benchmarkVerdict,
  ltvCacReference,
  cacPercent,
  channelOf,
} from "./marketingRules";
export type {
  RoasQuality,
  FunnelStep,
  FunnelRatio,
  FunnelCounts,
  BenchmarkVerdict,
} from "./marketingRules";
export { channelRoas, channelRoasSummary, channelsFromSales, siteChannel } from "./channelRoas";
export {
  marketingTabs,
  investmentMetrics,
  sessionMetrics,
  utmDimensions,
  adLevels,
  adPlatformFilters,
  adMetrics,
  marketingSearchSchema,
  defaultMarketingSearch,
} from "./marketingSchema";
export type {
  MarketingTab,
  InvestmentMetric,
  SessionMetric,
  UtmDimension,
  AdLevel,
  AdPlatformFilter,
  AdMetric,
  MarketingSearch,
} from "./marketingSchema";
