/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as dashboardRouteImport } from './routes/dashboard'
import { Route as assistantRouteImport } from './routes/assistant'
import { Route as customersRouteImport } from './routes/customers'
import { Route as connectionsRouteImport } from './routes/connections'
import { Route as moneyRouteImport } from './routes/money'
import { Route as managementRouteImport } from './routes/management'
import { Route as logisticsRouteImport } from './routes/logistics'
import { Route as marketingRouteImport } from './routes/marketing'
import { Route as ordersRouteImport } from './routes/orders'
import { Route as productsRouteImport } from './routes/products'

const dashboardRoute = dashboardRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const assistantRoute = assistantRouteImport.update({
  id: '/assistente',
  path: '/assistente',
  getParentRoute: () => rootRouteImport,
} as any)
const customersRoute = customersRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const connectionsRoute = connectionsRouteImport.update({
  id: '/conexoes',
  path: '/conexoes',
  getParentRoute: () => rootRouteImport,
} as any)
const moneyRoute = moneyRouteImport.update({
  id: '/dinheiro',
  path: '/dinheiro',
  getParentRoute: () => rootRouteImport,
} as any)
const managementRoute = managementRouteImport.update({
  id: '/gestao',
  path: '/gestao',
  getParentRoute: () => rootRouteImport,
} as any)
const logisticsRoute = logisticsRouteImport.update({
  id: '/logistica',
  path: '/logistica',
  getParentRoute: () => rootRouteImport,
} as any)
const marketingRoute = marketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const ordersRoute = ordersRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => rootRouteImport,
} as any)
const productsRoute = productsRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof dashboardRoute
  '/assistente': typeof assistantRoute
  '/clientes': typeof customersRoute
  '/conexoes': typeof connectionsRoute
  '/dinheiro': typeof moneyRoute
  '/gestao': typeof managementRoute
  '/logistica': typeof logisticsRoute
  '/marketing': typeof marketingRoute
  '/pedidos': typeof ordersRoute
  '/produtos': typeof productsRoute
}
export interface FileRoutesByTo {
  '/': typeof dashboardRoute
  '/assistente': typeof assistantRoute
  '/clientes': typeof customersRoute
  '/conexoes': typeof connectionsRoute
  '/dinheiro': typeof moneyRoute
  '/gestao': typeof managementRoute
  '/logistica': typeof logisticsRoute
  '/marketing': typeof marketingRoute
  '/pedidos': typeof ordersRoute
  '/produtos': typeof productsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof dashboardRoute
  '/assistente': typeof assistantRoute
  '/clientes': typeof customersRoute
  '/conexoes': typeof connectionsRoute
  '/dinheiro': typeof moneyRoute
  '/gestao': typeof managementRoute
  '/logistica': typeof logisticsRoute
  '/marketing': typeof marketingRoute
  '/pedidos': typeof ordersRoute
  '/produtos': typeof productsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assistente'
    | '/clientes'
    | '/conexoes'
    | '/dinheiro'
    | '/gestao'
    | '/logistica'
    | '/marketing'
    | '/pedidos'
    | '/produtos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assistente'
    | '/clientes'
    | '/conexoes'
    | '/dinheiro'
    | '/gestao'
    | '/logistica'
    | '/marketing'
    | '/pedidos'
    | '/produtos'
  id:
    | '__root__'
    | '/'
    | '/assistente'
    | '/clientes'
    | '/conexoes'
    | '/dinheiro'
    | '/gestao'
    | '/logistica'
    | '/marketing'
    | '/pedidos'
    | '/produtos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  dashboardRoute: typeof dashboardRoute
  assistantRoute: typeof assistantRoute
  customersRoute: typeof customersRoute
  connectionsRoute: typeof connectionsRoute
  moneyRoute: typeof moneyRoute
  managementRoute: typeof managementRoute
  logisticsRoute: typeof logisticsRoute
  marketingRoute: typeof marketingRoute
  ordersRoute: typeof ordersRoute
  productsRoute: typeof productsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof dashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistente': {
      id: '/assistente'
      path: '/assistente'
      fullPath: '/assistente'
      preLoaderRoute: typeof assistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof customersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conexoes': {
      id: '/conexoes'
      path: '/conexoes'
      fullPath: '/conexoes'
      preLoaderRoute: typeof connectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dinheiro': {
      id: '/dinheiro'
      path: '/dinheiro'
      fullPath: '/dinheiro'
      preLoaderRoute: typeof moneyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gestao': {
      id: '/gestao'
      path: '/gestao'
      fullPath: '/gestao'
      preLoaderRoute: typeof managementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logistica': {
      id: '/logistica'
      path: '/logistica'
      fullPath: '/logistica'
      preLoaderRoute: typeof logisticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketing': {
      id: '/marketing'
      path: '/marketing'
      fullPath: '/marketing'
      preLoaderRoute: typeof marketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedidos': {
      id: '/pedidos'
      path: '/pedidos'
      fullPath: '/pedidos'
      preLoaderRoute: typeof ordersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtos': {
      id: '/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof productsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  dashboardRoute: dashboardRoute,
  assistantRoute: assistantRoute,
  customersRoute: customersRoute,
  connectionsRoute: connectionsRoute,
  moneyRoute: moneyRoute,
  managementRoute: managementRoute,
  logisticsRoute: logisticsRoute,
  marketingRoute: marketingRoute,
  ordersRoute: ordersRoute,
  productsRoute: productsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
