/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConexoesRouteImport } from './routes/conexoes'
import { Route as DinheiroRouteImport } from './routes/dinheiro'
import { Route as GestaoRouteImport } from './routes/gestao'
import { Route as LogisticaRouteImport } from './routes/logistica'
import { Route as MarketingRouteImport } from './routes/marketing'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConexoesRoute = ConexoesRouteImport.update({
  id: '/conexoes',
  path: '/conexoes',
  getParentRoute: () => rootRouteImport,
} as any)
const DinheiroRoute = DinheiroRouteImport.update({
  id: '/dinheiro',
  path: '/dinheiro',
  getParentRoute: () => rootRouteImport,
} as any)
const GestaoRoute = GestaoRouteImport.update({
  id: '/gestao',
  path: '/gestao',
  getParentRoute: () => rootRouteImport,
} as any)
const LogisticaRoute = LogisticaRouteImport.update({
  id: '/logistica',
  path: '/logistica',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingRoute = MarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/conexoes': typeof ConexoesRoute
  '/dinheiro': typeof DinheiroRoute
  '/gestao': typeof GestaoRoute
  '/logistica': typeof LogisticaRoute
  '/marketing': typeof MarketingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/conexoes': typeof ConexoesRoute
  '/dinheiro': typeof DinheiroRoute
  '/gestao': typeof GestaoRoute
  '/logistica': typeof LogisticaRoute
  '/marketing': typeof MarketingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/conexoes': typeof ConexoesRoute
  '/dinheiro': typeof DinheiroRoute
  '/gestao': typeof GestaoRoute
  '/logistica': typeof LogisticaRoute
  '/marketing': typeof MarketingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/conexoes' | '/dinheiro' | '/gestao' | '/logistica' | '/marketing'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/conexoes' | '/dinheiro' | '/gestao' | '/logistica' | '/marketing'
  id:
    | '__root__'
    | '/'
    | '/conexoes'
    | '/dinheiro'
    | '/gestao'
    | '/logistica'
    | '/marketing'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConexoesRoute: typeof ConexoesRoute
  DinheiroRoute: typeof DinheiroRoute
  GestaoRoute: typeof GestaoRoute
  LogisticaRoute: typeof LogisticaRoute
  MarketingRoute: typeof MarketingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conexoes': {
      id: '/conexoes'
      path: '/conexoes'
      fullPath: '/conexoes'
      preLoaderRoute: typeof ConexoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dinheiro': {
      id: '/dinheiro'
      path: '/dinheiro'
      fullPath: '/dinheiro'
      preLoaderRoute: typeof DinheiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gestao': {
      id: '/gestao'
      path: '/gestao'
      fullPath: '/gestao'
      preLoaderRoute: typeof GestaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logistica': {
      id: '/logistica'
      path: '/logistica'
      fullPath: '/logistica'
      preLoaderRoute: typeof LogisticaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketing': {
      id: '/marketing'
      path: '/marketing'
      fullPath: '/marketing'
      preLoaderRoute: typeof MarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConexoesRoute: ConexoesRoute,
  DinheiroRoute: DinheiroRoute,
  GestaoRoute: GestaoRoute,
  LogisticaRoute: LogisticaRoute,
  MarketingRoute: MarketingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
